from pathlib import Path
import csv, html, json, shutil
root=Path(r'C:\Users\root\Downloads\КАРТА')
data=root/'projects'/'odh-yandex-export'/'data'
out=Path(r'C:\Users\root\Documents\Codex\2026-08-24\odh-yandex-export-tool\outputs')
# Existing project output directory (also exposed by the user-facing outputs junction).\nout.mkdir(parents=True,exist_ok=True)
rows=list(csv.DictReader((data/'current_wave1_historical_pdf_review.csv').open(encoding='utf-8-sig'),delimiter=';'))
for src,dst in [(data/'current_wave1_historical_pdf_review.csv',out/'odh_97_историческая_очередность_проверка.csv'),(data/'current_wave1_historical_pdf_review.md',out/'odh_97_историческая_очередность_проверка.md'),(root/'work_pdf_analysis'/'current_wave1_pdf_candidate_centroids.png',out/'odh_97_сверка_с_историческим_pdf.png')]: shutil.copy2(src,dst)
labels={'1':('Историческая 1-я очередь','Красная разметка PDF','#d9362b'),'2':('Историческая 2-я очередь','Синяя разметка PDF','#173fa5'),'3':('Историческая 3-я очередь','Зелёная разметка PDF','#2caa39'),'':('Не определено автоматически','Требуется ручная сверка','#66737a')}
by={k:[r for r in rows if r['old_queue_candidate']==k] for k in ['1','2','3','']}
def table(rs):
  body=''.join('<tr><td>{}</td><td>{}</td><td>{}%</td><td>{}</td><td>{} / {} / {}</td></tr>'.format(html.escape(r['id']),html.escape(r['name']),round(float(r['confidence'])*100),html.escape(r['review_status']),r['red_score'],r['blue_score'],r['green_score']) for r in rs)
  return '<table><thead><tr><th>ID ОДХ</th><th>Наименование</th><th>Уверенность</th><th>Статус</th><th>Баллы PDF: 1 / 2 / 3</th></tr></thead><tbody>'+body+'</tbody></table>'
sections=[]
for k in ['1','2','3','']:
 title,sub,col=labels[k];rs=by[k]
 sections.append('<details open><summary><span class="dot" style="background:{}"></span><span><b>{}</b><small>{}</small></span><strong>{}</strong></summary>{}</details>'.format(col,html.escape(title),html.escape(sub),len(rs),table(rs)))
cards=''.join('<div class="card"><div class="num" style="color:{}">{}</div><b>{}</b><small>{}</small></div>'.format(labels[k][2],len(by[k]),html.escape(labels[k][0]),html.escape(labels[k][1])) for k in ['1','2','3'])+'<div class="card"><div class="num">{}</div><b>Ручная сверка</b><small>точечные объекты или нет считываемого цвета</small></div>'.format(len(by['']))
page='''<!doctype html><html lang="ru"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Сверка очередности ОДХ — 97 позиций</title><style>
:root{--ink:#112d40;--muted:#5d7180;--paper:#f7f5ef;--line:#d6e1e5;--accent:#07877d}*{box-sizing:border-box}body{margin:0;background:var(--paper);font:15px/1.45 "Century Gothic",Arial,sans-serif;color:var(--ink)}main{max-width:1160px;margin:auto;padding:32px 24px 50px}header{display:flex;justify-content:space-between;align-items:flex-start;gap:24px;border-bottom:1px solid var(--line);padding-bottom:18px}.eyebrow{color:var(--accent);font-size:11px;font-weight:800;letter-spacing:.13em}h1{font-size:30px;margin:6px 0}p{max-width:800px;color:var(--muted)}.pill{display:inline-flex;padding:7px 10px;border:1px solid #e7c57a;border-radius:20px;background:#fff8e8;color:#6d5120;font-size:12px;font-weight:700}.cards{display:grid;grid-template-columns:repeat(4,1fr);gap:12px;margin:22px 0}.card{padding:15px;border:1px solid var(--line);border-radius:12px;background:white}.num{font-size:28px;font-weight:800}.card small,summary small{display:block;color:var(--muted);font-size:11px}.preview{width:100%;border:1px solid var(--line);border-radius:12px;background:white;margin:8px 0 20px}details{border:1px solid var(--line);border-radius:12px;background:#fff;margin:10px 0;overflow:hidden}summary{display:flex;align-items:center;gap:10px;padding:13px 16px;cursor:pointer;list-style:none}summary::-webkit-details-marker{display:none}summary strong{margin-left:auto;font-size:20px}.dot{width:12px;height:12px;border-radius:50%;flex:none}table{border-collapse:collapse;width:100%;font-size:12px}th,td{text-align:left;padding:9px 12px;border-top:1px solid var(--line);vertical-align:top}th{color:#49606d;background:#f3f7f7}td:first-child{font-family:Consolas,monospace;white-space:nowrap}@media(max-width:700px){.cards{grid-template-columns:repeat(2,1fr)}main{padding:22px 12px}h1{font-size:24px}table{font-size:10px}th,td{padding:7px 5px}}
</style><body><main><header><div><div class="eyebrow">СВЕРКА ИСТОРИЧЕСКОЙ РАЗМЕТКИ</div><h1>ОДХ: текущие 97 позиций 1-й очереди</h1><p>Сопоставление текущих объектов с цветами старого PDF. Молжаниновский район учтён как часть САО: его отдельная врезка на PDF обработана в общей ведомости.</p></div><span class="pill">Не внесено в публичную карту</span></header><section class="cards">{cards}</section><h2>Визуальная проверка привязки</h2><p>Точки — центроиды текущих объектов; их цвет — кандидат исторической очереди. Это контрольная иллюстрация, а не новый слой очередности.</p><img class="preview" src="odh_97_сверка_с_историческим_pdf.png" alt="Сверка текущих объектов с историческим PDF">{sections}<p><b>Методика.</b> Цвета считываются только с дорожных линий исторического PDF после отдельной привязки основной части карты и врезки Молжаниновского. Для каждого объекта сохранены баллы красного/синего/зелёного и статус проверки. Перед переносом результатов в интерактивную карту нужна содержательная проверка списка.</p></main></body></html>'''.replace('{cards}',cards).replace('{sections}',''.join(sections))
(out/'odh_97_историческая_очередность_проверка.html').write_text(page,encoding='utf-8')
print('written',len(rows),'records to',out)


